/* Generated By:JavaCC: Do not edit this line. RuleParserConstants.java */
package com.sun.ecperf.ruleengine;

public interface RuleParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 11;
  int MULTI_LINE_COMMENT = 12;
  int ABSTRACT = 14;
  int BOOLEAN = 15;
  int BREAK = 16;
  int BYTE = 17;
  int CASE = 18;
  int CATCH = 19;
  int CHAR = 20;
  int CLASS = 21;
  int CONST = 22;
  int CONTINUE = 23;
  int _DEFAULT = 24;
  int DO = 25;
  int DOUBLE = 26;
  int ELSE = 27;
  int EXTENDS = 28;
  int FALSE = 29;
  int FINAL = 30;
  int FINALLY = 31;
  int FLOAT = 32;
  int FOR = 33;
  int GOTO = 34;
  int IF = 35;
  int IMPLEMENTS = 36;
  int IMPORT = 37;
  int INSTANCEOF = 38;
  int INT = 39;
  int INTERFACE = 40;
  int LONG = 41;
  int NATIVE = 42;
  int NEW = 43;
  int NULL = 44;
  int PACKAGE = 45;
  int PRIVATE = 46;
  int PROTECTED = 47;
  int PUBLIC = 48;
  int RETURN = 49;
  int SHORT = 50;
  int STATIC = 51;
  int SUPER = 52;
  int SWITCH = 53;
  int SYNCHRONIZED = 54;
  int THIS = 55;
  int THROW = 56;
  int THROWS = 57;
  int TRANSIENT = 58;
  int TRUE = 59;
  int TRY = 60;
  int VOID = 61;
  int VOLATILE = 62;
  int WHILE = 63;
  int INTEGER_LITERAL = 64;
  int DECIMAL_LITERAL = 65;
  int HEX_LITERAL = 66;
  int OCTAL_LITERAL = 67;
  int FLOATING_POINT_LITERAL = 68;
  int EXPONENT = 69;
  int CHARACTER_LITERAL = 70;
  int STRING_LITERAL = 71;
  int IDENTIFIER = 72;
  int LETTER = 73;
  int DIGIT = 74;
  int LPAREN = 75;
  int RPAREN = 76;
  int LBRACE = 77;
  int RBRACE = 78;
  int LBRACKET = 79;
  int RBRACKET = 80;
  int SEMICOLON = 81;
  int COMMA = 82;
  int DOT = 83;
  int ASSIGN = 84;
  int GT = 85;
  int LT = 86;
  int BANG = 87;
  int TILDE = 88;
  int HOOK = 89;
  int COLON = 90;
  int EQ = 91;
  int LE = 92;
  int GE = 93;
  int NE = 94;
  int SC_OR = 95;
  int SC_AND = 96;
  int INCR = 97;
  int DECR = 98;
  int PLUS = 99;
  int MINUS = 100;
  int STAR = 101;
  int SLASH = 102;
  int BIT_AND = 103;
  int BIT_OR = 104;
  int XOR = 105;
  int REM = 106;
  int LSHIFT = 107;
  int RSIGNEDSHIFT = 108;
  int RUNSIGNEDSHIFT = 109;
  int PLUSASSIGN = 110;
  int MINUSASSIGN = 111;
  int STARASSIGN = 112;
  int SLASHASSIGN = 113;
  int ANDASSIGN = 114;
  int ORASSIGN = 115;
  int XORASSIGN = 116;
  int REMASSIGN = 117;
  int LSHIFTASSIGN = 118;
  int RSIGNEDSHIFTASSIGN = 119;
  int RUNSIGNEDSHIFTASSIGN = 120;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 10>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 13>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
