#!/usr/bin/perl -w

use Deluge::Config;
use Deluge::Mcp;

# -------------------------------------------------------------------

package main;

&main();
exit(0);

# -------------------------------------------------------------------

sub usage
{
    my ($comment) = @_;

	print STDERR "USAGE: dlg_proxy {configuration file} {user_def name}\n";

	($comment) && (print STDERR "ERROR: $comment\n");

	exit (1);
}

# -------------------------------------------------------------------

sub main
{
	my ($mcp, $cfg, $cfgfile, $defname);

	($#ARGV == -1) && (&usage());
	($#ARGV == 1) || (&usage("Incorrect number of parameters"));

	$cfgfile = shift(@ARGV);
	$defname = shift(@ARGV);

	$cfg = Deluge::Config->new($cfgfile);
	$mcp = Deluge::Mcp->new($cfg, 1);
	
	$mcp->prep_for_record($defname);
	$mcp->start_proxy();
	$mcp->shut_down();
}

