/**
    Copyright (C) 2004 Emre Kiciman and Stanford University

    This file is part of Pinpoint

    Pinpoint is free software; you can distribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    Pinpoint is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Pinpoint; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
**/
package roc.pinpoint.analysis.plugins2.jagr;

// marked for release 1.0

import java.util.*;

import roc.pinpoint.analysis.*;
import roc.pinpoint.analysis.structure.*;
import roc.pinpoint.injection.FaultTrigger;


/**
 * @author emrek
 *
 */
public class GenerateRRFaultloads implements Plugin, RecordCollectionListener {

    public static final String INPUT_COLLECTION_NAME_ARG = "inputCollection";
    public static final String OUTPUT_COLLECTION_NAME_ARG = "outputCollection";
    public static final String DEFINING_ATTRS_ARG = "definingAttrs";


    public static final String[] FAULT_TYPES = {
        "nullmap",
        "exception",
        "error",
        //"microreboot",
        //"full-reboot",
        //"memory-leak",
        "unbind",
        "deadlock",
        "infinite-loop"
    };

    PluginArg[] args = {
	new PluginArg( INPUT_COLLECTION_NAME_ARG,
		       "input collection.  this plugin will look for components in this record collection",
		       PluginArg.ARG_RECORDCOLLECTION,
		       true,
		       null ),
	new PluginArg( OUTPUT_COLLECTION_NAME_ARG,
		       "output collection.  this plugin will save String records(the xml fault configs) into this collection",
		       PluginArg.ARG_RECORDCOLLECTION,
		       true,
		       null ),
	new PluginArg( DEFINING_ATTRS_ARG,
		       "defining attributes of a component",
		       PluginArg.ARG_LIST,
		       true,
		       null )
    };

    RecordCollection inputRecordCollection;
    RecordCollection outputRecordCollection;
    Collection definingAttrs;

    HashSet alreadyProcessed;

    public PluginArg[] getPluginArguments() {
	return args;
    }

    /**
     * @see roc.pinpoint.analysis.Plugin#start(java.lang.String, java.util.Map, roc.pinpoint.analysis.AnalysisEngine)
     */
    public void start(String id, Map args, AnalysisEngine engine)
        throws PluginException {

        inputRecordCollection =
	    (RecordCollection) args.get(INPUT_COLLECTION_NAME_ARG);
	outputRecordCollection =
	    (RecordCollection) args.get(OUTPUT_COLLECTION_NAME_ARG);
        definingAttrs = (Collection)args.get( DEFINING_ATTRS_ARG );

	alreadyProcessed = new HashSet();

	inputRecordCollection.registerListener( this );
    }

    /**
     * @see roc.pinpoint.analysis.Plugin#stop()
     */
    public void stop() throws PluginException {
        inputRecordCollection.unregisterListener(this);
	alreadyProcessed = null;
    }

    /**
     * @see roc.pinpoint.analysis.RecordCollectionListener#addedRecords(java.lang.String, java.util.List)
     */
    public synchronized void addedRecord(String collectionName, Record rec) {
        Component c = (Component)rec.getValue();

        Map id = IdentifiableHelper.ReduceMap( c.getId(), definingAttrs );

        if( alreadyProcessed.contains( id ))
            return;

        outputFaultConfig( id );
        alreadyProcessed.add( id );
    }

    void outputFaultConfig( Map id ) {
	String fc1 = 
	    "<fault-injections>" + 
	    "<!-- AutoGenerated Config for " + id.toString() + "-->\n" +
	    "<";
        String fc2 = "> " +
	    "<jndi-name>";

	String fc3 = 
	    "</jndi-name> " +
            "<time-second>60</time-second> " +
	    "</";

        String fc4 = ">\n" +
            "</fault-injections>";

	String componentId = (String)id.get("name");

	for( int i=0; i < FAULT_TYPES.length; i++ ) {
	    String fc = 
		fc1 + 
                FAULT_TYPES[i] +
		fc2 +
		componentId +
		fc3 +
                FAULT_TYPES[i] +
                fc4;
	    
	    Record rec = new Record( fc );
	    outputRecordCollection.setRecord( componentId + "-" + 
                                              FAULT_TYPES[i] + ".xml", rec );
	}

    }
    

    /**
     * @see roc.pinpoint.analysis.RecordCollectionListener#removedRecords(java.lang.String, java.util.List)
     */
    public void removedRecords(String collectionName, List items) {
    }

}
